Repository dshreddy/SoftwareEngineering2024, pull requests merged in 2024-11, with the labels that each got.

#11 Bug Fix in logical operator
  FileCloner/Models/NetworkService/Client.cs
Labels: bug-fix

#15 UI improvements
  FileCloner/Views/MainPage.xaml
Labels: ui

#14 LOGGER ADDED AND A BUG FIX
  FileCloner/FileClonerLogging/FileClonerLogger.cs
  FileCloner/Models/FileExplorerServiceProvider.cs
  FileCloner/Models/NetworkService/Client.cs
  FileCloner/Models/NetworkService/Server.cs
  FileCloner/Models/SummaryGenerator.cs
  FileCloner/ViewModels/MainPageViewModel.FileWatcher.cs
  FileCloner/ViewModels/MainPageViewModel.TreeViewUpdater.cs
Labels: enhancement, bug-fix
